export const ADD_SERVICE_TO_CART_REQUEST = "ADD_SERVICE_TO_CART_REQUEST";
export const ADD_SERVICE_TO_CART_SUCCESS = "ADD_SERVICE_TO_CART_SUCCESS";
export const ADD_SERVICE_TO_CART_FAIL = "ADD_SERVICE_TO_CART_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";