export const PLACE_SERVICE_ORDER_REQUEST = "PLACE_SERVICE_ORDER_REQUEST";
export const PLACE_SERVICE_ORDER_SUCCESS = "PLACE_SERVICE_ORDER_SUCCESS";
export const PLACE_SERVICE_ORDER_FAIL = "PLACE_SERVICE_ORDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";