export const REGISTER_PROFESSIONAL_SUCCESS = 'REGISTER_PROFESSIONAL_SUCCESS';
export const REGISTER_PROFESSIONAL_REQUEST = 'REGISTER_PROFESSIONAL_REQUEST';
export const REGISTER_PROFESSIONAL_FAIL = 'REGISTER_PROFESSIONAL_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';