export const REGISTER_PROFESSIONAL_SUCCESS = 'REGISTER_PROFESSIONAL_SUCCESS';
export const REGISTER_PROFESSIONAL_REQUEST = 'REGISTER_PROFESSIONAL_REQUEST';
export const REGISTER_PROFESSIONAL_FAIL = 'REGISTER_PROFESSIONAL_FAIL';

export const SETUP_PROFILE_SUCCESS = 'SETUP_PROFILE_SUCCESS';
export const SETUP_PROFILE_REQUEST = 'SETUP_PROFILE_REQUEST';
export const SETUP_PROFILE_FAIL = 'SETUP_PROFILE_FAIL';
export const SETUP_PROFILE_RESET = 'SETUP_PROFILE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';